version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
      - frontend
    volumes:
      - ./:/app
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.subscription-system-secure.rule=Host(`payoon.dev`)'
      - 'traefik.http.services.subscription-system.loadbalancer.server.port=8090'
      - 'traefik.http.routers.subscription-system-secure.tls=true'
      - "traefik.http.routers.subscription-system-secure.tls.certresolver=le"
    env_file:
      - ./.env
networks:
  backend:
    external: true
  frontend:
    external: true